cache:
  key:
    files:
      - package-lock.json
  paths:
    - .npm

variables:
  AUTO_DEVOPS_BUILD_IMAGE_CNB_ENABLED: "true"
  AUTO_DEVOPS_BUILD_IMAGE_CNB_BUILDER: "heroku/buildpacks:20"
  npm_config_cache: "$CI_PROJECT_DIR/.npm"
  NEW_RELIC_ENABLED: "false"
  NEW_RELIC_NO_CONFIG_FILE: "true"

.build:
  stage: build
  image: "node:20.10.0-bullseye"
  cache: []
  environment:
    action: prepare
  artifacts:
    when: on_success
    paths:
      - dist/
  allow_failure: false
  before_script:
    - npm ci
  script:
    - apt update && apt install -y curl gnupg
    - curl -Ls --tlsv1.2 --proto "=https" --retry 3 https://cli.doppler.com/install.sh | sh
    - doppler run --token $DOPPLER_TOKEN -- npm run build

build_ax:
  extends: .build
  environment:
    name: ax
  variables:
    DOPPLER_TOKEN: $DOPPLER_TOKEN_AX
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - when: manual

.deploy:
  stage: deploy
  image: registry.gitlab.com/static-web-apps/azure-static-web-apps-deploy
  variables:
    APP_PATH: '$CI_PROJECT_DIR/dist'
    SKIP_APP_BUILD: true
    SKIP_API_BUILD: true
  script:
    - echo "Deploying SWA."

deploy_ax:
  extends: .deploy
  environment: ax
  resource_group: ax
  variables:
    API_TOKEN: $AZURE_SWA_API_TOKEN_AX
  needs:
    - job: build_ax
      artifacts: true
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: on_success

build_production:
  stage: build
  image: "docker:20.10.6"
  cache: {}
  variables:
    DOCKER_TLS_CERTDIR: ""
    MOUNT_POINT: /builds/$CI_PROJECT_PATH/mnt
  services:
    - docker:20.10.6-dind
  script:
    - |
      if [[ -z "$CI_COMMIT_TAG" ]]; then
        export CI_APPLICATION_REPOSITORY=${CI_APPLICATION_REPOSITORY:-$CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG}
        export CI_APPLICATION_TAG=${CI_APPLICATION_TAG:-$CI_COMMIT_SHA}
      else
        export CI_APPLICATION_REPOSITORY=${CI_APPLICATION_REPOSITORY:-$CI_REGISTRY_IMAGE}
        export CI_APPLICATION_TAG=${CI_APPLICATION_TAG:-$CI_COMMIT_TAG}
      fi
    - export image_tagged="$CI_APPLICATION_REPOSITORY:$CI_APPLICATION_TAG"
    - export image_cache="$CI_REGISTRY_IMAGE/cache-image:latest"
    - export image_latest="$CI_APPLICATION_REPOSITORY:latest"
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - apk add --update curl tar
    # install buildpacks tool
    - (curl -sSL "https://github.com/buildpacks/pack/releases/download/v0.26.0/pack-v0.26.0-linux.tgz" | tar -C /usr/local/bin/ --no-same-owner -xzv pack)
    # install and configure doppler cli
    - wget -q -t3 'https://packages.doppler.com/public/cli/rsa.8004D9FF50437357.key' -O /etc/apk/keys/cli@doppler-8004D9FF50437357.rsa.pub
    - echo 'https://packages.doppler.com/public/cli/alpine/any-version/main' | tee -a /etc/apk/repositories
    - apk add doppler
    - mkdir -p "$MOUNT_POINT"
    # build
    # Node.js 17+ uses OpenSSL 3 which enforces stricter crypto policies, 
    # leading to errors in some crypto operations.
    # The 'openssl-legacy-provider' option allows older crypto methods for compatibility.
    # TODO: Remove the NODE_OPTIONS env when webpack is updated to v5 and there are no build issues.
    - |
      doppler run --token "$DOPPLER_TOKEN_PRODUCTION" \
      --mount "$MOUNT_POINT/.doppler_env" \
      --mount-template .doppler_env.tmpl -- \
          pack build "$image_tagged"-production \
            --env-file "$MOUNT_POINT/.doppler_env" \
            --env "VUE_APP_VERSION=$CI_COMMIT_SHA-production" \
            --env "NODE_OPTIONS=--openssl-legacy-provider" \
            --creation-time now \
            --builder heroku/buildpacks:20 \
            --buildpack registry.gitlab.com/upchieve/doppler-buildpack \
            --buildpack heroku/nodejs@2.6.2 \
            --buildpack heroku/procfile@0.6.2
    - docker push "$image_tagged"-production
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'

build_demo:
  stage: build
  image: "docker:20.10.6"
  cache: {}
  when: manual
  allow_failure: true
  variables:
    DOCKER_TLS_CERTDIR: ""
    MOUNT_POINT: /builds/$CI_PROJECT_PATH/mnt
  services:
    - docker:20.10.6-dind
  script:
    - |
      if [[ -z "$CI_COMMIT_TAG" ]]; then
        export CI_APPLICATION_REPOSITORY=${CI_APPLICATION_REPOSITORY:-$CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG}
        export CI_APPLICATION_TAG=${CI_APPLICATION_TAG:-$CI_COMMIT_SHA}
      else
        export CI_APPLICATION_REPOSITORY=${CI_APPLICATION_REPOSITORY:-$CI_REGISTRY_IMAGE}
        export CI_APPLICATION_TAG=${CI_APPLICATION_TAG:-$CI_COMMIT_TAG}
      fi
    - export image_tagged="$CI_APPLICATION_REPOSITORY:$CI_APPLICATION_TAG"
    - export image_cache="$CI_REGISTRY_IMAGE/cache-image:latest"
    - export image_latest="$CI_APPLICATION_REPOSITORY:latest"
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - apk add --update curl tar
    # install buildpacks tool
    - (curl -sSL "https://github.com/buildpacks/pack/releases/download/v0.26.0/pack-v0.26.0-linux.tgz" | tar -C /usr/local/bin/ --no-same-owner -xzv pack)
    # install and configure doppler cli
    - wget -q -t3 'https://packages.doppler.com/public/cli/rsa.8004D9FF50437357.key' -O /etc/apk/keys/cli@doppler-8004D9FF50437357.rsa.pub
    - echo 'https://packages.doppler.com/public/cli/alpine/any-version/main' | tee -a /etc/apk/repositories
    - apk add doppler
    - mkdir -p "$MOUNT_POINT"
    # build
    # Node.js 17+ uses OpenSSL 3 which enforces stricter crypto policies, 
    # leading to errors in some crypto operations.
    # The 'openssl-legacy-provider' option allows older crypto methods for compatibility.
    # TODO: Remove the NODE_OPTIONS env when webpack is updated to v5 and there are no build issues.
    - |
      doppler run --token "$DOPPLER_TOKEN_DEMO" \
      --mount "$MOUNT_POINT/.doppler_env" \
      --mount-template .doppler_env.tmpl -- \
          pack build "$image_tagged"-demo \
            --env-file "$MOUNT_POINT/.doppler_env" \
            --env "VUE_APP_VERSION=$CI_COMMIT_SHA-demo" \
            --env "NODE_OPTIONS=--openssl-legacy-provider" \
            --creation-time now \
            --builder heroku/buildpacks:20 \
            --buildpack registry.gitlab.com/upchieve/doppler-buildpack \
            --buildpack heroku/nodejs@2.6.2 \
            --buildpack heroku/procfile@0.6.2
    - docker push "$image_tagged"-demo
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'

build_staging:
  stage: build
  image: "docker:20.10.6"
  cache: {}
  variables:
    DOCKER_TLS_CERTDIR: ""
    MOUNT_POINT: /builds/$CI_PROJECT_PATH/mnt
  services:
    - docker:20.10.6-dind
  script:
    - |
      if [[ -z "$CI_COMMIT_TAG" ]]; then
        export CI_APPLICATION_REPOSITORY=${CI_APPLICATION_REPOSITORY:-$CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG}
        export CI_APPLICATION_TAG=${CI_APPLICATION_TAG:-$CI_COMMIT_SHA}
      else
        export CI_APPLICATION_REPOSITORY=${CI_APPLICATION_REPOSITORY:-$CI_REGISTRY_IMAGE}
        export CI_APPLICATION_TAG=${CI_APPLICATION_TAG:-$CI_COMMIT_TAG}
      fi
    - export image_tagged="$CI_APPLICATION_REPOSITORY:$CI_APPLICATION_TAG"
    - export image_cache="$CI_REGISTRY_IMAGE/cache-image:latest"
    - export image_latest="$CI_APPLICATION_REPOSITORY:latest"
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - apk add --update curl tar
    # install buildpacks tool
    - (curl -sSL "https://github.com/buildpacks/pack/releases/download/v0.26.0/pack-v0.26.0-linux.tgz" | tar -C /usr/local/bin/ --no-same-owner -xzv pack)
    # install and configure doppler cli
    - wget -q -t3 'https://packages.doppler.com/public/cli/rsa.8004D9FF50437357.key' -O /etc/apk/keys/cli@doppler-8004D9FF50437357.rsa.pub
    - echo 'https://packages.doppler.com/public/cli/alpine/any-version/main' | tee -a /etc/apk/repositories
    - apk add doppler
    - mkdir -p "$MOUNT_POINT"
    # build
    # Node.js 17+ uses OpenSSL 3 which enforces stricter crypto policies, 
    # leading to errors in some crypto operations.
    # The 'openssl-legacy-provider' option allows older crypto methods for compatibility.
    # TODO: Remove the NODE_OPTIONS env when webpack is updated to v5 and there are no build issues.
    - |
      doppler run --token "$DOPPLER_TOKEN_STAGING" \
      --mount "$MOUNT_POINT/.doppler_env" \
      --mount-template .doppler_env.tmpl -- \
          pack build "$image_tagged"-staging \
            --env-file "$MOUNT_POINT/.doppler_env" \
            --env "VUE_APP_VERSION=$CI_COMMIT_SHA-staging" \
            --env "NODE_OPTIONS=--openssl-legacy-provider" \
            --creation-time now \
            --builder heroku/buildpacks:20 \
            --buildpack registry.gitlab.com/upchieve/doppler-buildpack \
            --buildpack heroku/nodejs@2.6.2 \
            --buildpack heroku/procfile@0.6.2
    - docker push "$image_tagged"-staging
  rules:
    - if: '$CI_COMMIT_BRANCH != "main"'
      when: always
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: manual

build_hackers:
  stage: build
  image: "docker:20.10.6"
  cache: {}
  when: manual
  allow_failure: true
  variables:
    DOCKER_TLS_CERTDIR: ""
    MOUNT_POINT: /builds/$CI_PROJECT_PATH/mnt
  services:
    - docker:20.10.6-dind
  script:
    - |
      if [[ -z "$CI_COMMIT_TAG" ]]; then
        export CI_APPLICATION_REPOSITORY=${CI_APPLICATION_REPOSITORY:-$CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG}
        export CI_APPLICATION_TAG=${CI_APPLICATION_TAG:-$CI_COMMIT_SHA}
      else
        export CI_APPLICATION_REPOSITORY=${CI_APPLICATION_REPOSITORY:-$CI_REGISTRY_IMAGE}
        export CI_APPLICATION_TAG=${CI_APPLICATION_TAG:-$CI_COMMIT_TAG}
      fi
    - export image_tagged="$CI_APPLICATION_REPOSITORY:$CI_APPLICATION_TAG"
    - export image_cache="$CI_REGISTRY_IMAGE/cache-image:latest"
    - export image_latest="$CI_APPLICATION_REPOSITORY:latest"
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - apk add --update curl tar
    # install buildpacks tool
    - (curl -sSL "https://github.com/buildpacks/pack/releases/download/v0.26.0/pack-v0.26.0-linux.tgz" | tar -C /usr/local/bin/ --no-same-owner -xzv pack)
    # install and configure doppler cli
    - wget -q -t3 'https://packages.doppler.com/public/cli/rsa.8004D9FF50437357.key' -O /etc/apk/keys/cli@doppler-8004D9FF50437357.rsa.pub
    - echo 'https://packages.doppler.com/public/cli/alpine/any-version/main' | tee -a /etc/apk/repositories
    - apk add doppler
    - mkdir -p "$MOUNT_POINT"
    # build
    # Node.js 17+ uses OpenSSL 3 which enforces stricter crypto policies, 
    # leading to errors in some crypto operations.
    # The 'openssl-legacy-provider' option allows older crypto methods for compatibility.
    # TODO: Remove the NODE_OPTIONS env when webpack is updated to v5 and there are no build issues.
    - |
      doppler run --token "$DOPPLER_TOKEN_HACKERS" \
      --mount "$MOUNT_POINT/.doppler_env" \
      --mount-template .doppler_env.tmpl -- \
          pack build "$image_tagged"-hackers \
            --env-file "$MOUNT_POINT/.doppler_env" \
            --env "VUE_APP_VERSION=$CI_COMMIT_SHA-hackers" \
            --env "NODE_OPTIONS=--openssl-legacy-provider" \
            --creation-time now \
            --builder heroku/buildpacks:20 \
            --buildpack registry.gitlab.com/upchieve/doppler-buildpack \
            --buildpack heroku/nodejs@2.6.2 \
            --buildpack heroku/procfile@0.6.2
    - docker push "$image_tagged"-hackers
  rules:
    - if: '$CI_COMMIT_BRANCH != "main"'
      when: manual
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: manual

test:
  stage: test
  image: node:20.10.0-bullseye
  before_script:
    - npm ci --cache .npm --prefer-offline
  script:
    - npm run test
  needs: []
  rules:
    - if: '$TEST_DISABLED'
      when: never
    - if: '$CI_COMMIT_TAG || $CI_COMMIT_BRANCH'

lint:
  stage: test
  image: node:20.10.0-bullseye
  before_script:
    - npm ci --cache .npm --prefer-offline
  script:
    - npm run lint:dry
  needs: []
  rules:
    - if: '$TEST_DISABLED'
      when: never
    - if: '$CI_COMMIT_TAG || $CI_COMMIT_BRANCH'

html_validate:
  stage: test
  image: node:20.10.0-bullseye
  allow_failure: true
  before_script:
    - npm ci --cache .npm --prefer-offline
  script:
    - npm run html-validate
  needs: []
  rules:
    - if: '$TEST_DISABLED'
      when: never
    - if: '$CI_COMMIT_TAG || $CI_COMMIT_BRANCH'
