<template>
  <div>
    <div class="main">
      <div class="student-header">
        <div class="student-info">
          <div class="img-container">
            <student-avatar class="img"></student-avatar>
          </div>
          <div class="student-info-text">
            <h1>{{ studentFirstName }} {{ studentLastName }}</h1>
            <h2>{{ className }}</h2>
          </div>
        </div>
      </div>
      <div class="filter-container">
        <div class="filter-controls">
          <FormSelect
            v-if="topics.length"
            class="topics-dropdown"
            name="topic"
            label="Subject"
            :placeholder="subjectPlaceholder"
            :optionTextField="'displayName'"
            :reduce="(option) => option.name"
            :options="[
              ...topics,
              { name: 'other', displayName: 'All Subjects' },
            ]"
            v-model="filters.topic.name"
            @update:modelValue="submitFilter"
          />
          <div class="date-input-container">
            <FormDateInput
              label="From"
              id="session-activity-from"
              :placeholder="filters.sessionActivityFrom"
              v-model="filters.sessionActivityFrom"
              @update:modelValue="submitFilter"
            />
            <FormDateInput
              label="To"
              id="session-activity-to"
              :placeholder="filters.sessionActivityTo"
              v-model="filters.sessionActivityTo"
              @update:modelValue="submitFilter"
            />
          </div>
        </div>
      </div>
      <div></div>
      <div class="sessions-container">
        <loader v-if="isLoading" />
        <div class="sessions-header">
          <div class="header-item">Subject</div>
          <div class="header-item"># of Messages</div>
          <div class="header-item">Session Date</div>
          <div class="header-item">Session Length</div>
        </div>

        <div
          v-for="session in sessions"
          :key="session.id"
          class="session-group"
          :class="hasSessionSummary ? 'has-summary' : ''"
        >
          <div
            class="session-row"
            :class="hasSessionSummary && !session.summary ? 'summary-row' : ''"
          >
            <div class="session-item">
              <b v-if="session.summary">{{ session.sessionSubject }}</b
              ><span v-else>{{ session.sessionSubject }}</span>
            </div>
            <div class="session-item">{{ session.messageCount }}</div>
            <div class="session-item">
              {{ formatTimestamp(session.createdAt) }}
            </div>
            <div class="session-item">{{ session.length }} Minutes</div>
          </div>
          <div class="summary-row" v-if="session.summary">
            <div class="session-summary-wrapper">
              <div class="session-summary">
                <div class="icon-and-tooltip">
                  <BlueAlert class="alert-icon" />
                  <div class="summary-tooltip">
                    This summary was generated by AI and may not be 100%
                    accurate.
                  </div>
                </div>
                {{ session.summary.summary }}
              </div>
              <div class="summary-feedback">
                <span>Was this summary helpful?</span>
                <GenerationFeedback
                  name="session-review-feedback"
                  :analyticsServiceThumbsUp="{
                    eventName: EVENTS.SESSION_SUMMARY_THUMBS_UP,
                    eventData: { sessionId: session.id },
                  }"
                  :analyticsServiceThumbsDown="{
                    eventName: EVENTS.SESSION_SUMMARY_THUMBS_DOWN,
                    eventData: { sessionId: session.id },
                  }"
                  :analyticsServiceFollowup="{
                    eventName: EVENTS.SESSION_SUMMARY_FEEDBACK,
                  }"
                  :traceId="session.summary.traceId"
                />
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
import Loader from '@/components/Loader.vue'
import FormDateInput from '@/components/FormInputs/FormDateInput.vue'
import NetworkService from '@/services/NetworkService'
import { mapState } from 'vuex'
import StudentAvatar from '@/assets/user_avatars/student-avatar.svg'
import { dayjs } from '@/utils/time-utils'
import FormSelect from '@/components/FormInputs/FormSelect.vue'
import BlueAlert from '@/assets/blue-alert.svg'
import GenerationFeedback from '@/components/GenerationFeedback.vue'
import { EVENTS } from '@/consts'
import { getCurrentSchoolYearStartDate } from '@/utils/time-utils'

export default {
  name: 'student-details',
  components: {
    Loader,
    StudentAvatar,
    FormDateInput,
    FormSelect,
    BlueAlert,
    GenerationFeedback,
  },

  inject: ['classData'],

  data() {
    return {
      studentId: '',
      sessions: [],
      studentFirstName: '',
      studentLastName: '',
      isLoading: true,
      filters: {
        topic: {
          name: '',
        },
        sessionActivityFrom:
          getCurrentSchoolYearStartDate().format('YYYY-MM-DD'),
        sessionActivityTo: dayjs().format('YYYY-MM-DD'),
      },
      subjectPlaceholder: '',
      hasSessionSummary: false,
      EVENTS,
    }
  },
  computed: {
    className() {
      return this.classData?.name ?? ''
    },
    ...mapState({
      topics: (state) => state.subjects.topics,
      subjects: (state) => state.subjects.subjects,
    }),
  },

  async created() {
    this.studentId = this.$route.params.studentId

    await this.$store.dispatch('subjects/awaitTopics')
    if (this.classData?.topicId) {
      const topic = this.topics.find((t) => t.id === this.classData.topicId)
      this.filters.topic.name = topic.name
      this.subjectPlaceholder = topic.displayName
    } else {
      this.filters.topic.name = 'other'
      this.subjectPlaceholder = 'All Subjects'
    }

    this.sessions = await this.getStudentSessionDetails()
  },

  methods: {
    formatTimestamp(timestamp) {
      const date = dayjs(timestamp)
      return date.format('MM/DD/YYYY')
    },

    async getStudentSessionDetails() {
      this.isLoading = true
      try {
        const {
          data: { sessionDetails },
        } = await NetworkService.getStudentSessionDetails(this.studentId)

        const filteredSessionDetails = sessionDetails.sort(
          (a, b) => new Date(b.createdAt) - new Date(a.createdAt)
        )

        if (filteredSessionDetails.length === 0) {
          return []
        }

        this.studentFirstName = filteredSessionDetails[0].firstName
        this.studentLastName = filteredSessionDetails[0].lastName
        const subjects = this.subjects
        const sessionsWithSubjects = filteredSessionDetails.map((session) => {
          const created = new Date(session.createdAt)
          const ended = new Date(session.endedAt)
          const sessionLength = (ended - created) / (1000 * 60)
          if (session.summary) this.hasSessionSummary = true
          return {
            ...session,
            sessionSubject: subjects[session.name].displayName,
            length: Math.round(sessionLength),
          }
        })
        return this.filterSessions(
          sessionsWithSubjects,
          this.subjects,
          this.filters
        )
      } catch {
        return []
      } finally {
        this.isLoading = false
      }
    },

    filterSessions(sessions, subjects, filters) {
      const start = new Date(filters.sessionActivityFrom + 'T00:00')
      const end = new Date(filters.sessionActivityTo + 'T23:59:59')
      const filteredSubjects = Object.values(subjects)
        .filter(
          (subject) =>
            filters.topic.name === 'other' ||
            subject.topicName === filters.topic.name
        )
        .map((subject) => subject.name)

      const filtered = sessions.filter((session) => {
        const createdAt = new Date(session.createdAt)
        return (
          createdAt >= start &&
          createdAt <= end &&
          filteredSubjects.includes(session.name)
        )
      })

      return filtered
    },

    async submitFilter() {
      this.sessions = await this.getStudentSessionDetails()
    },
  },
}
</script>

<style lang="scss" scoped>
h1 {
  font-size: 24px;
  margin-bottom: 4px;
}

h2 {
  font-size: 16px;
  margin: 0;
}

.main {
  @include flex-container(column, center);
}

.student-info {
  @include flex-container(row);
}

.sessions-container {
  @include flex-container(column, center, center);
}

.img-container {
  @include flex-container(column, flex-end, center);
  background: $c-student;
  width: 40px;
  height: 40px;
  border-radius: 50%;
  overflow: hidden;
  margin-right: 12px;
}

.img {
  max-width: 100%;
  max-height: 100%;
}

.student-info-text {
  @include flex-container(column, flex-start, flex-start);
}

.sessions-header {
  @include flex-container(row);
  background-color: #e3f2fd;
  padding: 8px 12px;
  font-size: 16px;
  font-weight: 500;
  text-align: left;
  width: 100%;
  border-radius: 8px;

  @include breakpoint-below('small') {
    font-size: 12px;
    padding: 2px;
  }
}

.header-item {
  flex: 1;
  padding: 8px 12px;
}

.session-group {
  @include flex-container(column);
  margin: 16px 0;
  width: 100%;
}

.session-group.has-summary {
  border-left: 6px solid #e3f2fd;

  .session-item {
    padding-left: 0;
  }
}

.session-row {
  @include flex-container(row);
  width: 100%;
  padding: 8px 0 16px 20px;
}

.session-item {
  flex: 1;
  font-size: 16px;
  padding-left: 8px;
}

.summary-row {
  border-bottom: 2px solid $c-border-grey;
  padding: 0 0 16px 20px;
  font-size: 16px;
}

.session-summary-wrapper {
  position: relative;
}

.summary-tooltip {
  position: absolute;
  top: 100%;
  left: 0;
  width: auto;
  background-color: #eeeeee;
  padding: 8px;
  margin-top: 4px;
  border: 1px solid #ccc;
  border-radius: 4px;
  white-space: normal;
  box-shadow: -2px 6px 10px rgba(0, 0, 0, 0.2);
  z-index: 10;
  display: none;
}

.session-summary {
  @include flex-container(row, flex-start, center);
}

.summary-feedback {
  margin-top: 16px;
  span {
    font-weight: 500;
  }
}

.icon-and-tooltip:hover .summary-tooltip {
  display: block;
}

.alert-icon {
  margin-right: 8px;
  cursor: default;
}

.topics-dropdown {
  background-color: #ffffff;
  border-radius: 5px;
  margin-right: 10px;
}

.filter-container {
  @include flex-container(column, flex-start);
  border-radius: 8px;
  margin-top: 8px;

  @include breakpoint-below('small') {
    @include flex-container(row, center);
    max-width: 100%;
  }
}

.filter-controls {
  @include flex-container(row, center);
  width: 100%;
  max-width: 600px;
  margin-bottom: 10px;
  align-items: center;

  @include breakpoint-below('medium') {
    @include flex-container(column, center);
  }
}

.select-label {
  flex: 1;
  margin-right: 10px;

  @include breakpoint-below('medium') {
    width: 100%;
    margin: 0;
  }
}

.date-input-container {
  @include flex-container(row, center, space-between);
  gap: 10px;
  @include breakpoint-below('medium') {
    @include flex-container(column, center);
    width: 100%;
  }
}

.date-label {
  @include flex-container(column, center, flex-start);
  margin-right: 10px;

  @include breakpoint-below('medium') {
    width: 100%;
  }
}
</style>
