/** Maximum width considered to still be in "mobile mode." */
export const MAX_MOBILE_MODE_WIDTH = 768 - 1 // 768 = "medium" scss breakpoint

export const LATEST_APP_VERSION = '1.1.0'

export const APP_STORE_LINK =
  'https://apps.apple.com/us/app/upchieve/id1506076042'

export const GOOGLE_PLAY_STORE_LINK =
  'https://play.google.com/store/apps/details?id=org.upchieve.mobile'

export const CDN_URL = 'https://upchievecdn.blob.core.windows.net'

export const DOCS_URL = `${CDN_URL}/docs`

export const GRADES = [
  '6th grade',
  '7th grade',
  '8th grade',
  '9th grade',
  '10th grade',
  '11th grade',
  '12th grade',
  'College',
  'Other',
]

export const STATES = [
  'Alabama',
  'Alaska',
  'Arizona',
  'Arkansas',
  'California',
  'Colorado',
  'Connecticut',
  'Delaware',
  'Florida',
  'Georgia',
  'Hawaii',
  'Idaho',
  'Illinois',
  'Indiana',
  'Iowa',
  'Kansas',
  'Kentucky',
  'Louisiana',
  'Maine',
  'Maryland',
  'Massachusetts',
  'Michigan',
  'Minnesota',
  'Mississippi',
  'Missouri',
  'Montana',
  'Nebraska',
  'Nevada',
  'New Hampshire',
  'New Jersey',
  'New Mexico',
  'New York',
  'North Carolina',
  'North Dakota',
  'Ohio',
  'Oklahoma',
  'Oregon',
  'Pennsylvania',
  'Puerto Rico',
  'Rhode Island',
  'South Carolina',
  'South Dakota',
  'Tennessee',
  'Texas',
  'Utah',
  'Vermont',
  'Virginia',
  'Washington',
  'West Virginia',
  'Wisconsin',
  'Wyoming',
]

export const COUNTRIES = [
  'United States of America',
  'Afghanistan',
  'Albania',
  'Algeria',
  'American Samoa',
  'Andorra',
  'Angola',
  'Anguilla',
  'Antarctica',
  'Antigua and Barbuda',
  'Argentina',
  'Armenia',
  'Aruba',
  'Australia',
  'Austria',
  'Azerbaijan',
  'Bahamas',
  'Bahrain',
  'Bangladesh',
  'Barbados',
  'Belarus',
  'Belgium',
  'Belize',
  'Benin',
  'Bermuda',
  'Bhutan',
  'Bolivia (Plurinational State of)',
  'Bonaire, Sint Eustatius and Saba',
  'Bosnia and Herzegovina',
  'Botswana',
  'Bouvet Island',
  'Brazil',
  'British Indian Ocean Territory',
  'Brunei Darussalam',
  'Bulgaria',
  'Burkina Faso',
  'Burundi',
  'Cabo Verde',
  'Cambodia',
  'Cameroon',
  'Canada',
  'Cayman Islands',
  'Central African Republic',
  'Chad',
  'Chile',
  'China',
  'Christmas Island',
  'Cocos (Keeling) Islands',
  'Colombia',
  'Comoros',
  'Congo (the Democratic Republic of the)',
  'Congo',
  'Cook Islands',
  'Costa Rica',
  'Croatia',
  'Cuba',
  'Curaçao',
  'Cyprus',
  'Czechia',
  "Côte d'Ivoire",
  'Denmark',
  'Djibouti',
  'Dominica',
  'Dominican Republic',
  'Ecuador',
  'Egypt',
  'El Salvador',
  'Equatorial Guinea',
  'Eritrea',
  'Estonia',
  'Eswatini',
  'Ethiopia',
  'Falkland Islands',
  'Faroe Islands',
  'Fiji',
  'Finland',
  'France',
  'French Guiana',
  'French Polynesia',
  'French Southern Territories',
  'Gabon',
  'Gambia',
  'Georgia',
  'Germany',
  'Ghana',
  'Gibraltar',
  'Greece',
  'Greenland',
  'Grenada',
  'Guadeloupe',
  'Guam',
  'Guatemala',
  'Guernsey',
  'Guinea',
  'Guinea-Bissau',
  'Guyana',
  'Haiti',
  'Heard Island and McDonald Islands',
  'Holy See',
  'Honduras',
  'Hong Kong',
  'Hungary',
  'Iceland',
  'India',
  'Indonesia',
  'Iran (Islamic Republic of)',
  'Iraq',
  'Ireland',
  'Isle of Man',
  'Israel',
  'Italy',
  'Jamaica',
  'Japan',
  'Jersey',
  'Jordan',
  'Kazakhstan',
  'Kenya',
  'Kiribati',
  "Korea (the Democratic People's Republic of)",
  'Korea (the Republic of)',
  'Kuwait',
  'Kyrgyzstan',
  "Lao People's Democratic Republic",
  'Latvia',
  'Lebanon',
  'Lesotho',
  'Liberia',
  'Libya',
  'Liechtenstein',
  'Lithuania',
  'Luxembourg',
  'Macao',
  'Madagascar',
  'Malawi',
  'Malaysia',
  'Maldives',
  'Mali',
  'Malta',
  'Marshall Islands',
  'Martinique',
  'Mauritania',
  'Mauritius',
  'Mayotte',
  'Mexico',
  'Micronesia (Federated States of)',
  'Moldova (the Republic of)',
  'Monaco',
  'Mongolia',
  'Montenegro',
  'Montserrat',
  'Morocco',
  'Mozambique',
  'Myanmar',
  'Namibia',
  'Nauru',
  'Nepal',
  'Netherlands',
  'New Caledonia',
  'New Zealand',
  'Nicaragua',
  'Niger',
  'Nigeria',
  'Niue',
  'Norfolk Island',
  'Northern Mariana Islands',
  'Norway',
  'Oman',
  'Pakistan',
  'Palau',
  'Palestine, State of',
  'Panama',
  'Papua New Guinea',
  'Paraguay',
  'Peru',
  'Philippines',
  'Pitcairn',
  'Poland',
  'Portugal',
  'Puerto Rico',
  'Qatar',
  'Republic of North Macedonia',
  'Romania',
  'Russian Federation',
  'Rwanda',
  'Réunion',
  'Saint Barthélemy',
  'Saint Helena, Ascension and Tristan da Cunha',
  'Saint Kitts and Nevis',
  'Saint Lucia',
  'Saint Martin (French part)',
  'Saint Pierre and Miquelon',
  'Saint Vincent and the Grenadines',
  'Samoa',
  'San Marino',
  'Sao Tome and Principe',
  'Saudi Arabia',
  'Senegal',
  'Serbia',
  'Seychelles',
  'Sierra Leone',
  'Singapore',
  'Sint Maarten (Dutch part)',
  'Slovakia',
  'Slovenia',
  'Solomon Islands',
  'Somalia',
  'South Africa',
  'South Georgia and the South Sandwich Islands',
  'South Sudan',
  'Spain',
  'Sri Lanka',
  'Sudan',
  'Suriname',
  'Svalbard and Jan Mayen',
  'Sweden',
  'Switzerland',
  'Syrian Arab Republic',
  'Taiwan',
  'Tajikistan',
  'Tanzania, United Republic of',
  'Thailand',
  'Timor-Leste',
  'Togo',
  'Tokelau',
  'Tonga',
  'Trinidad and Tobago',
  'Tunisia',
  'Turkey',
  'Turkmenistan',
  'Turks and Caicos Islands',
  'Tuvalu',
  'Uganda',
  'Ukraine',
  'United Arab Emirates',
  'United Kingdom of Great Britain and Northern Ireland',
  'United States Minor Outlying Islands',
  'Uruguay',
  'Uzbekistan',
  'Vanuatu',
  'Venezuela (Bolivarian Republic of)',
  'Viet Nam',
  'Virgin Islands (British)',
  'Virgin Islands (U.S.)',
  'Wallis and Futuna',
  'Western Sahara',
  'Yemen',
  'Zambia',
  'Zimbabwe',
  'Aland Islands',
]

export const STATES_WITH_ABBREVIATIONS = [
  { label: 'Alabama', value: 'AL' },
  { label: 'Alaska', value: 'AK' },
  { label: 'American Samoa', value: 'AS' },
  { label: 'Arizona', value: 'AZ' },
  { label: 'Arkansas', value: 'AR' },
  { label: 'California', value: 'CA' },
  { label: 'Colorado', value: 'CO' },
  { label: 'Connecticut', value: 'CT' },
  { label: 'Delaware', value: 'DE' },
  { label: 'District of Columbia', value: 'DC' },
  { label: 'States of Micronesia', value: 'FM' },
  { label: 'Florida', value: 'FL' },
  { label: 'Georgia', value: 'GA' },
  { label: 'Guam', value: 'GU' },
  { label: 'Hawaii', value: 'HI' },
  { label: 'Idaho', value: 'ID' },
  { label: 'Illinois', value: 'IL' },
  { label: 'Indiana', value: 'IN' },
  { label: 'Iowa', value: 'IA' },
  { label: 'Kansas', value: 'KS' },
  { label: 'Kentucky', value: 'KY' },
  { label: 'Louisiana', value: 'LA' },
  { label: 'Maine', value: 'ME' },
  { label: 'Marshall Islands', value: 'MH' },
  { label: 'Maryland', value: 'MD' },
  { label: 'Massachusetts', value: 'MA' },
  { label: 'Michigan', value: 'MI' },
  { label: 'Minnesota', value: 'MN' },
  { label: 'Mississippi', value: 'MS' },
  { label: 'Missouri', value: 'MO' },
  { label: 'Montana', value: 'MT' },
  { label: 'Nebraska', value: 'NE' },
  { label: 'Nevada', value: 'NV' },
  { label: 'New Hampshire', value: 'NH' },
  { label: 'New Jersey', value: 'NJ' },
  { label: 'New Mexico', value: 'NM' },
  { label: 'New York', value: 'NY' },
  { label: 'North Carolina', value: 'NC' },
  { label: 'North Dakota', value: 'ND' },
  { label: 'Northern Mariana Islands', value: 'MP' },
  { label: 'Ohio', value: 'OH' },
  { label: 'Oklahoma', value: 'OK' },
  { label: 'Oregon', value: 'OR' },
  { label: 'Palau', value: 'PW' },
  { label: 'Pennsylvania', value: 'PA' },
  { label: 'Puerto Rico', value: 'PR' },
  { label: 'Rhode Island', value: 'RI' },
  { label: 'South Carolina', value: 'SC' },
  { label: 'South Dakota', value: 'SD' },
  { label: 'Tennessee', value: 'TN' },
  { label: 'Texas', value: 'TX' },
  { label: 'Utah', value: 'UT' },
  { label: 'Vermont', value: 'VT' },
  { label: 'Virgin Islands', value: 'VI' },
  { label: 'Virginia', value: 'VA' },
  { label: 'Washington', value: 'WA' },
  { label: 'West Virginia', value: 'WV' },
  { label: 'Wisconsin', value: 'WI' },
  { label: 'Wyoming', value: 'WY' },
]

// user events in a [noun][verb] format
export const EVENTS = {
  ACCOUNT_CREATED: 'ACCOUNT_CREATED',
  ACCOUNT_DEACTIVATED: 'ACCOUNT_DEACTIVATED',
  ACCOUNT_VERIFIED: 'ACCOUNT_VERIFIED',
  AVAILABILITY_UPDATED: 'AVAILABILITY_UPDATED',
  BACKGROUND_INFORMATION_COMPLETED: 'BACKGROUND_INFORMATION_COMPLETED',
  // @note: eligibility does not follow [noun][verb] format
  ELIGIBILITY_ELIGIBLE: 'ELIGIBILITY_ELIGIBLE',
  ELIGIBILITY_INELIGIBLE: 'ELIGIBILITY_INELIGIBLE',
  PHOTO_ID_ADDED: 'PHOTO_ID_ADDED',
  PROFILE_UPDATED: 'PROFILE_UPDATED',
  POST_SESSION_SURVEY_SUBMITTED: 'POST_SESSION_SURVEY_SUBMITTED',
  QUIZ_STARTED: 'QUIZ_STARTED',
  QUIZ_PASSED: 'QUIZ_PASSED',
  QUIZ_FAILED: 'QUIZ_FAILED',
  GLEAP_BOT_SHOWN: 'GLEAP_BOT_SHOWN',
  GLEAP_CLOSED: 'GLEAP_CLOSED',
  GLEAP_SURVEY_SHOWN: 'GLEAP_SURVEY_SHOWN',
  GLEAP_NEWS_ARTICLE_SHOWN: 'GLEAP_NEWS_ARTICLE_SHOWN',
  REFERENCE_ADDED: 'REFERENCE_ADDED',
  REFERENCE_FORM_SUBMITTED: 'REFERENCE_FORM_SUBMITTED',
  REVIEW_MATERIALS_VIEWED: 'REVIEW_MATERIALS_VIEWED',
  SESSION_ENDED: 'SESSION_ENDED',
  SESSION_REQUESTED: 'SESSION_REQUESTED',
  SESSION_TIMED_OUT_15_MINS: 'SESSION_TIMED_OUT_15_MINS',
  SESSION_TIMED_OUT_45_MINS: 'SESSION_TIMED_OUT_45_MINS',
  STUDENT_SHOWN_ONBOARDING_MODAL: 'STUDENT_SHOWN_ONBOARDING_MODAL',
  STUDENT_FINISHED_ONBOARDING_MODAL: 'STUDENT_FINISHED_ONBOARDING_MODAL',
  STUDENT_CLICKED_CANT_FIND_SCHOOL: 'STUDENT_CLICKED_CANT_FIND_SCHOOL',
  STUDENT_CLICKED_CHECK_MY_ELIGIBILITY: 'STUDENT_CLICKED_CHECK_MY_ELIGIBILITY',
  STUDENT_CLICKED_STUDENT_ACCESS_PAGE: 'STUDENT_CLICKED_STUDENT_ACCESS_PAGE',
  STUDENT_CLICKED_CREATE_ACCOUNT: 'STUDENT_CLICKED_CREATE_ACCOUNT',
  STUDENT_ENTERED_EMAIL: 'STUDENT_ENTERED_EMAIL',
  STUDENT_ENTERED_FIRST_NAME: 'STUDENT_ENTERED_FIRST_NAME',
  STUDENT_ENTERED_INVALID_PASSWORD: 'STUDENT_ENTERED_INVALID_PASSWORD', // pragma: allowlist secret
  STUDENT_ENTERED_LAST_NAME: 'STUDENT_ENTERED_LAST_NAME',
  STUDENT_ENTERED_PASSWORD: 'STUDENT_ENTERED_PASSWORD', // pragma: allowlist secret
  STUDENT_ENTERED_ZIP_CODE: 'STUDENT_ENTERED_ZIP_CODE',
  STUDENT_SEARCHED_SCHOOL: 'STUDENT_SEARCHED_SCHOOL',
  STUDENT_SELECTED_SCHOOL: 'STUDENT_SELECTED_SCHOOL',
  STUDENT_SELECTED_GRADE: 'STUDENT_SELECTED_GRADE',
  STUDENT_SELECTED_HOW_DID_YOU_HEAR_ABOUT_US:
    'STUDENT_SELECTED_HOW_DID_YOU_HEAR_ABOUT_US',
  STUDENT_VISITED_DEACTIVATED_PARTNER: 'STUDENT_VISITED_DEACTIVATED_PARTNER',
  STUDENT_TELL_THEM_CP_MODAL_SHOWN: 'STUDENT_TELL_THEM_CP_MODAL_SHOWN',
  STUDENT_TELL_THEM_CP_REMINDER: 'STUDENT_TELL_THEM_CP_REMINDER',
  STUDENT_TELL_THEM_CP_STARTED_SESSION: 'STUDENT_TELL_THEM_CP_STARTED_SESSION',
  STUDENT_TELL_THEM_CP_ENTERED_REMINDER_DATE:
    'STUDENT_TELL_THEM_CP_ENTERED_REMINDER_DATE',
  STUDENT_TELL_THEM_CP_CLICKED_REMIND_ME:
    'STUDENT_TELL_THEM_CP_CLICKED_REMIND_ME',
  STUDENT_TELL_THEM_CP_CLICKED_NOT_INTERESTED:
    'STUDENT_TELL_THEM_CP_CLICKED_NOT_INTERESTED',
  STUDENT_TELL_THEM_CP_CANCEL_CONFIRMATION:
    'STUDENT_TELL_THEM_CP_CANCEL_CONFIRMATION',
  STUDENT_TELL_THEM_CP_CLICKED_DONT_REMIND_ME:
    'STUDENT_TELL_THEM_CP_CLICKED_DONT_REMIND_ME',
  STUDENT_TELL_THEM_CP_CLICKED_BACK_BUTTON:
    'STUDENT_TELL_THEM_CP_CLICKED_BACK_BUTTON',
  VOLUNTEER_CLICKED_ABOUT_SESSION: 'VOLUNTEER_CLICKED_ABOUT_SESSION',
  VOLUNTEER_FAST_TRACKED: 'VOLUNTEER_FAST_TRACKED',
  VOLUNTEER_VISITED_DEACTIVATED_PARTNER:
    'VOLUNTEER_VISITED_DEACTIVATED_PARTNER',
  MATERIAL_COMPLETED: 'MATERIAL_COMPLETED',
  MATERIAL_VIEWED: 'MATERIAL_VIEWED',
  FLAGGED_AS_AUTO_FLOW_STEP_TWO_PROGRESS_BAR:
    'FLAGGED_AS_AUTO_FLOW_STEP_TWO_PROGRESS_BAR',
  FLAGGED_AS_AUTO_FLOW_STEP_TWO_AVAILBILITY_STEP:
    'FLAGGED_AS_AUTO_FLOW_STEP_TWO_AVAILBILITY_STEP',
  USER_DOES_NOT_HAVE_LINKED_GOOGLE_ACCOUNT:
    'USER_DOES_NOT_HAVE_LINKED_GOOGLE_ACCOUNT',
  USER_DOES_NOT_HAVE_LINKED_CLEVER_ACCOUNT:
    'USER_DOES_NOT_HAVE_LINKED_CLEVER_ACCOUNT',
  USER_CLICKED_SIGN_IN_WITH_GOOGLE: 'USER_CLICKED_SIGN_IN_WITH_GOOGLE',
  USER_CLICKED_SIGN_IN_WITH_CLEVER: 'USER_CLICKED_SIGN_IN_WITH_CLEVER',
  PARTNER_STUDENT_CLICKED_SIGN_UP_WITH_GOOGLE:
    'PARTNER_STUDENT_CLICKED_SIGN_UP_WITH_GOOGLE',
  USER_CLICKED_SIGN_UP_WITH_GOOGLE: 'USER_CLICKED_SIGN_UP_WITH_GOOGLE',
  USER_CLICKED_SIGN_UP_WITH_CLEVER: 'USER_CLICKED_SIGN_UP_WITH_CLEVER',
  USER_VISITED_REFERRAL_LINK: 'STUDENT_VISITED_REFERRAL_LINK',
  STUDENT_CLICKED_TO_GET_REFERRAL_LINK_CARD:
    'STUDENT_CLICKED_TO_GET_REFERRAL_LINK_CARD',
  STUDENT_SHOWN_REFERRAL_MODAL: 'STUDENT_SHOWN_REFERRAL_MODAL',
  STUDENT_CLICKED_REFER_A_FRIEND: 'STUDENT_CLICKED_REFER_A_FRIEND',
  STUDENT_COPIED_REFERRAL_LINK: 'STUDENT_COPIED_REFERRAL_LINK',
  USER_CLICKED_IN_SESSION_HELP: 'USER_CLICKED_IN_SESSION_HELP',
  CC_STUDENT_CLICKED_UPCHIEVE_LINK: 'CC_STUDENT_CLICKED_UPCHIEVE_LINK',
  PHONE_NUMBER_UPDATED: 'PHONE_NUMBER_UPDATED',
  SMS_OPTED_IN: 'SMS_OPTED_IN',
  SMS_OPTED_OUT: 'SMS_OPTED_OUT',
  SMS_CONSENT_CHECKBOX_CHANGED: 'SMS_CONSENT_CHECKBOX_CHANGED',
  PHONE_NUMBER_VERIFIED: 'PHONE_NUMBER_VERIFIED',
  PHONE_NUMBER_VERIFICATION_MODAL_OPENED:
    'PHONE_NUMBER_VERIFICATION_MODAL_OPENED',
  USER_CLICKED_PREVIOUS_SESSION_HISTORY_PAGE:
    'USER_CLICKED_PREVIOUS_SESSION_HISTORY_PAGE',
  USER_CLICKED_NEXT_SESSION_HISTORY_PAGE:
    'USER_CLICKED_NEXT_SESSION_HISTORY_PAGE',
  CHAT_BOT_GIVE_RESOURCES_MESSAGE_SHOWN:
    'CHAT_BOT_GIVE_RESOURCES_MESSAGE_SHOWN',
  CHAT_BOT_SEE_YOU_SOON_MESSAGE_SHOWN: 'CHAT_BOT_SEE_YOU_SOON_MESSAGE_SHOWN',
  SESSION_RECAP_DM_REPORT_MODAL_SHOWN: 'SESSION_RECAP_REPORT_MODAL_SHOWN',
  SESSION_RECAP_DM_REPORT_MODAL_SUBMITTED:
    'SESSION_RECAP_DM_REPORT_MODAL_SUBMITTED',
  BF_STUDENT_CLICKED_LEARN_MORE: 'BF_STUDENT_CLICKED_LEARN_MORE',
  BF_STUDENT_CLICKED_START_COLLEGE_SESSION:
    'BF_STUDENT_CLICKED_START_COLLEGE_SESSION',
  BF_STUDENT_SHOWED_START_COLLEGE_SESSION:
    'BF_STUDENT_SHOWED_START_COLLEGE_SESSION',
  SKIPPING_ELIGIBILITY_EMAIL: 'SKIPPING_ELIGIBILITY_EMAIL',
  VERIFICATION_HEADER_CLICKED: 'VERIFICATION_HEADER_CLICKED',
  VERIFICATION_MODAL_OPENED: 'VERIFICATION_MODAL_OPENED',
  EMAIL_VERIFIED: 'EMAIL_VERIFIED',
  EMAIL_UPDATED: 'EMAIL_UPDATED',
  PROGRESS_REPORT_SESSION_RECAP_STUDENT_REQUESTED_HELP:
    'PROGRESS_REPORT_SESSION_RECAP_STUDENT_REQUESTED_HELP',
  PROGRESS_REPORT_SESSION_RECAP_STUDENT_CLICKED_REPORT:
    'PROGRESS_REPORT_SESSION_RECAP_STUDENT_CLICKED_REPORT',
  PROGRESS_REPORT_OVERVIEW_OPENED: 'PROGRESS_REPORT_OVERVIEW_OPENED',
  PROGRESS_REPORT_OVERVIEW_SUBJECT_OPENED:
    'PROGRESS_REPORT_OVERVIEW_SUBJECT_OPENED',
  PROGRESS_REPORT_OVERVIEW_STUDENT_CLICKED_NEXT_PAGE:
    'PROGRESS_REPORT_OVERVIEW_STUDENT_CLICKED_NEXT_PAGE',
  PROGRESS_REPORT_OVERVIEW_STUDENT_CLICKED_PREVIOUS_PAGE:
    'PROGRESS_REPORT_OVERVIEW_STUDENT_CLICKED_PREVIOUS_PAGE',
  PROGRESS_REPORT_OVERVIEW_STUDENT_CLICKED_RECAP:
    'PROGRESS_REPORT_OVERVIEW_STUDENT_CLICKED_RECAP',
  PROGRESS_REPORT_OVERVIEW_STUDENT_REQUESTED_SESSION:
    'PROGRESS_REPORT_OVERVIEW_STUDENT_REQUESTED_SESSION',
  PROGRESS_REPORT_SURVEY_SUBMITTED: 'PROGRESS_REPORT_SURVEY_SUBMITTED',
  VOLUNTEER_JOINED_SESSION_FROM_NOTIFICATION:
    'VOLUNTEER_JOINED_SESSION_FROM_NOTIFICATION',
  VOLUNTEER_DISMISSED_NOTIFICATION: 'VOLUNTEER_DISMISSED_NOTIFICATION',
  NOTIFICATION_AUTO_CLOSED_AFTER_DURATION_REACHED:
    'NOTIFICATION_AUTO_CLOSED_AFTER_DURATION_REACHED',
  TEACHER_SEARCHED_SCHOOL: 'TEACHER_SEARCHED_SCHOOL',
  TEACHER_CLICKED_CANT_FIND_SCHOOL: 'TEACHER_CLICKED_CANT_FIND_SCHOOL',
  TEACHER_SELECTED_SCHOOL: 'TEACHER_SELECTED_SCHOOL',
  TEACHER_ENTERED_SIGNUP_SOURCE: 'TEACHER_ENTERED_SIGNUP_SOURCE',
  TEACHER_CLICKED_CHECK_ELIGIBILITY: 'TEACHER_CLICKED_CHECK_ELIGIBILITY',
  TEACHER_ELIGIBILITY_ELIGIBLE: 'TEACHER_ELIGIBILITY_ELIGIBLE',
  TEACHER_ELIGIBILITY_INELIGIBLE: 'TEACHER_ELIGIBILITY_INELIGIBLE',
  TEACHER_ENTERED_FIRST_NAME: 'TEACHER_ENTERED_FIRST_NAME',
  TEACHER_ENTERED_LAST_NAME: 'TEACHER_ENTERED_LAST_NAME',
  TEACHER_ENTERED_EMAIL: 'TEACHER_ENTERED_EMAIL',
  TEACHER_ENTERED_PASSWORD: 'TEACHER_ENTERED_PASSWORD', // pragma: allowlist secret
  TEACHER_CLICKED_CREATE_ACCOUNT: 'TEACHER_CLICKED_CREATE_ACCOUNT',
  USER_CLICKED_WHITEBOARD_ERASER_TOOL: 'USER_CLICKED_WHITEBOARD_ERASER_TOOL',
  USER_SOCKET_IS_CONNECTED_IN_SESSION: 'USER_SOCKET_IS_CONNECTED_IN_SESSION',
  USER_SOCKET_IS_DISCONNECTED_IN_SESSION:
    'USER_SOCKET_IS_DISCONNECTED_IN_SESSION',
  STUDENT_CLICKED_RECENT_SUBJECT: 'STUDENT_CLICKED_RECENT_SUBJECT',
  SELECTED_ABOUT_THIS_SESSION_RATING: 'SELECTED_ABOUT_THIS_SESSION_RATING',
  SUBMITTED_ABOUT_THIS_SESSION_COMMENTS:
    'SUBMITTED_ABOUT_THIS_SESSION_COMMENTS',
  USER_SHOWN_ABOUT_THIS_SESSION_SURVEY: 'USER_SHOWN_ABOUT_THIS_SESSION_SURVEY',
  BIG_FUTURE_STUDENT_SAW_EMAIL_ONLY_FLOW:
    'BIG_FUTURE_STUDENT_SAW_EMAIL_ONLY_FLOW',
  BIG_FUTURE_SUBMITTED_EMAIL_IN_EMAIL_ONLY_FLOW:
    'BIG_FUTURE_SUBMITTED_EMAIL_IN_EMAIL_ONLY_FLOW',
  BIG_FUTURE_STUDENT_SAW_GRADE_AND_SCHOOL_ONLY_FLOW:
    'BIG_FUTURE_STUDENT_SAW_GRADE_AND_SCHOOL_ONLY_FLOW',
  BIG_FUTURE_STUDENT_SHOWN_ZIP_CODE_ELIGIBILITY_FALL_BACK:
    'BIG_FUTURE_STUDENT_SHOWN_ZIP_CODE_ELIGIBILITY_FALL_BACK',
  VOICE_MESSAGE_RECORDING_BUTTON_SEEN: 'VOICE_MESSAGE_RECORDING_BUTTON_SEEN',
  VOICE_MESSAGE_START_RECORDING: 'VOICE_MESSAGE_START_RECORDING',
  VOICE_MESSAGE_STOP_RECORDING: 'VOICE_MESSAGE_STOP_RECORDING',
  VOICE_MESSAGE_SEND_RECORDING: 'VOICE_MESSAGE_SEND_RECORDING',
  VOICE_MESSAGE_SEND_RECORDING_ERRORED: 'VOICE_MESSAGE_SEND_RECORDING_ERRORED',
  VOICE_MESSAGE_DELETE_RECORDING: 'VOICE_MESSAGE_DELETE_RECORDING',
  VOICE_MESSAGE_HOVER_RECORDING_BUTTON: 'VOICE_MESSAGE_HOVER_RECORDING_BUTTON',
  VOICE_MESSAGE_MIC_ACCESS_DENIED: 'VOICE_MESSAGE_MIC_ACCESS_DENIED',
  VOICE_MESSAGE_PLAYED_OWN_MESSAGE_IN_CHAT:
    'VOICE_MESSAGE_PLAYED_OWN_MESSAGE_IN_CHAT',
  VOICE_MESSAGE_PLAYED_PARTNER_MESSAGE_IN_CHAT:
    'VOICE_MESSAGE_PLAYED_PARTNER_MESSAGE_IN_CHAT',
  VOICE_MESSAGE_ANNOUNCEMENT_SEEN: 'VOICE_MESSAGE_ANNOUNCEMENT_SEEN',
  VOICE_MESSAGE_ANNOUNCEMENT_CLOSED: 'VOICE_MESSAGE_ANNOUNCEMENT_CLOSED',
  VOICE_MESSAGE_VOICE_RECOGNITION_NOT_SUPPORTED:
    'VOICE_MESSAGE_VOICE_RECOGNITION_NOT_SUPPORTED',
  VOICE_MESSAGE_TRANSCRIPT_SENT: 'VOICE_MESSAGE_TRANSCRIPT_SENT',
  VOICE_MESSAGE_SEND_TRANSCRIPT_ERRORED:
    'VOICE_MESSAGE_SEND_TRANSCRIPT_ERRORED',
  STUDENT_ENTERED_CLASS_CODE: 'STUDENT_ENTERED_CLASS_CODE',
  STUDENT_ENTERED_EMAIL_ON_JOIN_CLASS: 'STUDENT_ENTERED_EMAIL_ON_JOIN_CLASS',
  STUDENT_SELECTED_GRADE_ON_JOIN_CLASS: 'STUDENT_SELECTED_GRADE_ON_JOIN_CLASS',
  STUDENT_CLICKED_JOIN_CLASS: 'STUDENT_CLICKED_JOIN_CLASS',
  STUDENT_REDIRECTED_TO_JOIN_CLASS_WITH_PARAMS: 'STUDENT_REDIRECTED_TO_JOIN_CLASS_WITH_PARAMS',
  STUDENT_JOINED_CLASS: 'STUDENT_JOINED_CLASS',
  STUDENT_JOIN_CLASS_REDIRECT_TO_LOGIN: 'STUDENT_JOIN_CLASS_REDIRECT_TO_LOGIN',
  STUDENT_JOIN_CLASS_REDIRECT_TO_SIGN_UP: 'STUDENT_JOIN_CLASS_REDIRECT_TO_SIGN_UP',
  INELIGIBLE_STUDENT_RETURNED_TO_SIGN_UP:
    'INELIGIBLE_STUDENT_RETURNED_TO_SIGN_UP',
  VOLUNTEER_CLICKED_UPLOAD_IMAGE: 'VOLUNTEER_CLICKED_UPLOAD_IMAGE',
  VOLUNTEER_UPLOADED_IMAGE: 'VOLUNTEER_UPLOADED_IMAGE',
  VOLUNTEER_IMAGE_CENSORED: 'VOLUNTEER_IMAGE_CENSORED',
  VOLUNTEER_IMAGE_MODERATION_FAILED: 'VOLUNTEER_IMAGE_MODERATION_FAILED',
  VOLUNTEER_IMAGE_UPLOAD_SEEN: 'VOLUNTEER_IMAGE_UPLOAD_SEEN',
}

export const VERIFICATION_METHOD = {
  SMS: 'sms',
  EMAIL: 'email',
}

export const POSTHOG_FEATURE_FLAGS = {
  FILTER_ACTIVE_SUBJECTS: 'filter-active-subjects',
  POLL_FLAGS: 'polling-flags',
  OFFER_GOOGLE_SSO: 'offer-google-sso',
  ORBITAL_SEGMENTS: 'orbital-segments',
  DOWNTIME_BANNER: 'downtime-banner',
  SUBJECT_REQUEST_ROLLOUT: 'subject-request-rollout',
  QUIZ_ROLLOUT: 'quiz-rollout',
  GLEAP_SEGMENT_EXPERIMENTS: 'gleap-segment-experiments',
  CC_INTRO_COPY: 'cc-intro-copy',
  BF_INTRO_COPY: 'bf-intro-copy',
  MUTED_SUBJECT_ALERTS: 'muted-subject-alerts',
  REFERRAL_COPY: 'referral-copy',
  SESSION_RECAP_DMS: 'session-recap-dms',
  DASHBOARD_REDESIGN: 'dashboard-redesign',
  FORCE_DASHBOARD_REDESIGN_ORG: 'force-dashboard-redesign-org',
  AUTO_START_COLLEGE_SESSION: 'auto-start-college-session',
  SMS_VERIFICATION: 'sms-verification',
  ELIGIBILITY_EMAIL: 'eligibility-email',
  PROGRESS_REPORTS: 'progress-reports',
  QUILL_V2: 'quill-v2',
  PROGRESS_REPORT_SURVEY: 'progress-report-survey',
  USE_NEW_SIGN_UP_FLOW: 'use-new-sign-up-flow',
  SHOW_IN_APP_SESSION_NOTIFICATIONS: 'show-in-app-session-notifications',
  WHITEBOARD_ERASER_TOOL: 'whiteboard-eraser-tool',
  SESSION_PRESENCE: 'session-presence',
  MOST_RECENT_SUBJECTS: 'most-recent-subjects',
  ABOUT_THIS_SESSION_SURVEY: 'about-this-session-feedback',
  BIG_FUTURE_EMAIL_ELIGIBILITY_FLOW: 'big-future-email-eligibility-flow',
  BIG_FUTURE_TWO_QUESTION_ELIGIBILITY_FLOW:
    'big-future-two-question-eligibility-flow',
  VOICE_MESSAGE: 'voice-message',
  VOLUNTEER_IMAGE_UPLOAD: 'volunteer-image-upload',
}

export const ANALYTICS_REPORT_ROW = {
  FIRST_NAME: 'First name',
  LAST_NAME: 'Last name',
  EMAIL: 'Email',
  STATE: 'State of residence',
  ONBOARDING_STATUS: 'Onboarding status',
  DATE_ACCOUNT_CREATED: 'Date of account creation',
  DATE_ONBOARDED: 'Date onboarded',
  DATE_FIRST_SESSION: 'Date of first session',
  CERTIFICATIONS_RECEIVED: 'Certifications received',
  MATH_CERTS_RECEIVED: 'Math certs received',
  SCIENCE_CERTS_RECEIVED: 'Science certs received',
  COLLEGE_CERTS_RECEIVED: 'College counseling received',
  TOTAL_TEXTS_RECEIVED: 'Total texts received',
  TOTAL_SESSIONS_COMPLETED: 'Total sessions completed',
  TOTAL_UNIQUE_STUDENTS_HELPED: 'Total unique students helped',
  TOTAL_TUTORING_HOURS: 'Total tutoring hours',
  TOTAL_TRAINING_HOURS: 'Total training hours',
  TOTAL_ELAPSED_AVAILABILITY_HOURS: 'Total elapsed availability hours',
  TOTAL_VOLUNTEER_HOURS: 'Total hours',
  DATE_RANGE_TEXTS_RECEIVED: 'Texts received within date range',
  DATE_RANGE_SESSIONS_COMPLETED: 'Sessions completed within date range',
  DATE_RANGE_UNIQUE_STUDENTS_HELPED: 'Unique students helped within date range',
  DATE_RANGE_TUTORING_HOURS: 'Tutoring hours within date range',
  DATE_RANGE_TRAINING_HOURS: 'Training hours within date range',
  DATE_RANGE_ELAPSED_AVAILABILITY_HOURS:
    'Elapsed availability hours within date range',
  DATE_RANGE_VOLUNTEER_HOURS: 'Total hours within date range',
}

export const ANALYTICS_REPORT_SUMMARY = {
  DATE_RANGE_SIGN_UPS: 'New sign-ups',
  DATE_RANGE_VOLUNTEERS_ONBOARDED: 'Volunteers onboarded',
  DATE_RANGE_TEXT_RECEIVED: 'Tutoring opportunities provided',
  DATE_RANGE_SESSIONS_COMPLETED: 'Sessions completed',
  DATE_RANGE_VOLUNTEER_HOURS: 'Volunteer hours completed',
  DATE_RANGE_UNIQUE_STUDENTS_HELPED: 'Unique students helped',
  TOTAL_SIGN_UPS: 'Total sign-ups',
  TOTAL_VOLUNTEERS_ONBORDED: 'Total volunteers onboarded',
  TOTAL_TEXTS_RECEIVED: 'Total tutoring opportunities provided',
  TOTAL_SESSIONS_COMPLETED: 'Total sessions completed',
  TOTAL_VOLUNTEER_HOURS: 'Total volunteer hours completed',
  TOTAL_UNIQUE_STUDENTS_HELPED: 'Total unique students helped',
}

export const QUESTION_TYPES = {
  multipleChoice: 'multiple choice',
  checkBox: 'check box',
  freeResponse: 'free response',
}

export const SESSION_TOOL_TYPES = {
  DOCUMENT_EDITOR: 'documenteditor',
  WHITEBOARD: 'whiteboard',
}

// The key is obfuscated to avoid users easily recognizing what it is
export const INELIGIBLE_LOCAL_STORAGE_KEY = '7x9h8'
